### ISSUE TITLE
Can not work with SwipeRefresh

### ISSUE THREAD

**Issue by LxzBUG** [EverythingMe/overscroll-decor#37] opened 2016-12-20 09:35 UTC
Can not work when recyclerView with SwipeRefresh  

and can not  use with Layout   

   LinearLayout llRootView=find...

 OverScrollDecoratorHelper.setUpStaticOverScroll(llRootView, OverScrollDecoratorHelper.ORIENTATION_VERTICAL);

can not

**Comment by d4vidi** [comment] 2017-04-25 19:58
Swipe-to-refresh: duplicate of issue #5.
Linear-layout can't work cause it's not scrollable...

**Closed by d4vidi** 2017-04-25 19:58 UTC
